export const MessageConstant = {
  REQUIRED: 'MESSAGE.REQUIRED',
  EMAIL: 'MESSAGE.EMAIL',
  RANGE_NUMBER: 'MESSAGE.RANGE_NUMBER',
  NUMBER: 'MESSAGE.NUMBER',
  ERROR_BORROWER_STATUS_REQUESTED: 'MESSAGE.ERROR_BORROWER_STATUS_REQUESTED',
  MAX_LENGTH: 'MESSAGE.MAX_LENGTH'
};
