export const PlaceholderConstant = {
  TYPE_NAME: 'PLACEHOLDER.TYPE_NAME',
  SEARCH_BY_TITLE_OR_BODY: 'PLACEHOLDER.SEARCH_BY_TITLE_OR_BODY',
  SEARCH_BY_NAME_OR_EMAIL_OR_PHONE: 'PLACEHOLDER.SEARCH_BY_NAME_OR_EMAIL_OR_PHONE'
};
